# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 05:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 7, 27, 5, 29, 50, 365323, tzinfo=utc)),
        ),
    ]
