# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-07 21:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160727_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 8, 7, 21, 44, 58, 465651, tzinfo=utc)),
        ),
    ]
