# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-08 00:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160808_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 8, 8, 0, 2, 26, 292420, tzinfo=utc)),
        ),
    ]
